import test from 'node:test';
import assert from 'node:assert/strict';
import {estimate,costBreakdown,validateResources,resourcePortfolio,safeSourceUrl} from '../dist/resources.mjs';
import {scenario,examples,sortMeasures} from '../dist/model.mjs';
const team={id:'team',name:'Plattform',role:'Integrasjon',fte:estimate(1,2,3),weeks:estimate(4,6,8),start:2,rate:10000,includeCost:true};
const t={...examples[0],id:'test',customers:100000,reach:100,value:8000,low:0,expected:.4,high:.8,cost:999999,setup:999999,
 costItems:[{name:'Lisens',kind:'annual',basis:'known',...estimate(120000)},{name:'Etablering',kind:'once',basis:'estimate',...estimate(100000,200000,300000)}],teams:[team]};
test('Kostnadsposter erstatter totalsummer, og team beregnes som FTE × uker × sats',()=>{assert.deepEqual(costBreakdown(t),{annual:120000,once:200000,labor:120000,total:440000,effort:12,duration:8});assert.equal(costBreakdown(t,'low').total,260000);assert.equal(costBreakdown(t,'high').total,660000)});
test('Lav verdi bruker høy kostnad, høy verdi bruker lav kostnad',()=>{assert.equal(scenario(t,'low').net,-660000);assert.equal(scenario(t).net,2760000);assert.equal(scenario(t,'high').net,6140000)});
test('Parallelle team summerer innsats, men ikke kalenderuker',()=>{const parallel={...t,teams:[team,{...team,id:'second',name:'Service',start:5,weeks:estimate(2,4,6)}]};assert.equal(costBreakdown(parallel).effort,20);assert.equal(costBreakdown(parallel).duration,9);assert.equal(costBreakdown(parallel,'high').duration,11)});
test('Team utelatt fra kostnad teller fortsatt i innsats og varighet',()=>{const x=costBreakdown({...t,teams:[{...team,includeCost:false}]});assert.equal(x.labor,0);assert.equal(x.effort,12);assert.equal(x.duration,8);assert.equal(x.total,320000)});
test('Kjente beløp, scenarioorden og 52-ukers grense valideres',()=>{assert.equal(validateResources(t),'');assert.ok(validateResources({...t,costItems:[{...t.costItems[0],low:0}]}));assert.ok(validateResources({...t,teams:[{...team,fte:estimate(3,2,1)}]}));assert.ok(validateResources({...t,teams:[{...team,start:45}]}));assert.equal(validateResources({...t,teams:[{...team,start:44}]}),'');assert.ok(validateResources({...t,teams:[{...team,rate:NaN}]}))});
test('Ingen rader gir null kostnad og ingen tids-/ressursanslag',()=>assert.deepEqual(costBreakdown({costItems:[],teams:[]}),{annual:0,once:0,labor:0,total:0,effort:0,duration:0}));
test('Porteføljen summerer like teamnavn uten å dobbelttelle antall tiltak',()=>{const result=resourcePortfolio([{...t,teams:[team,{...team,id:'x',name:' plattform '}]},{...t,id:'other',teams:[team]}]);assert.equal(result.length,1);assert.equal(result[0].measures,2);assert.equal(result[0].expected,36)});
test('Lavverdisortering bruker kostnadsusikkerhet',()=>{const a={...t,id:'a',name:'A',low:.4};const b={...a,id:'b',name:'B',costItems:[{name:'Fast',kind:'once',basis:'known',...estimate(400000)}],teams:[]};assert.equal(sortMeasures([a,b],'low')[0].id,'b')});

test('Kilder kan knyttes til churn, kostnad og team',()=>{const source={id:'ref1',title:'Tilbud v2',type:'vendor',url:'https://example.com/tilbud',version:'v2',note:'Testreferanse'};const linked={...t,sources:[source],effectSourceId:'ref1',costItems:t.costItems.map(r=>({...r,sourceId:'ref1'})),teams:[{...team,sourceId:'ref1'}]};assert.equal(validateResources(linked),'');assert.ok(validateResources({...linked,sources:[]}));assert.ok(validateResources({...linked,sources:[{...source,title:''}]}));assert.equal(validateResources({...linked,sources:[{...source,url:''}]}),'')});
test('Kildelenker avviser aktive protokoller og innebygde passord',()=>{assert.equal(safeSourceUrl('javascript:alert(1)'),null);assert.equal(safeSourceUrl('data:text/html,test'),null);assert.equal(safeSourceUrl('https://user:pass@example.com'),null);assert.equal(safeSourceUrl('https://example.com/report'),'https://example.com/report')});
